//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_America {
        displayName = "The Resistance ";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\nato_ca.paa";
        priority = 0;
    };
};//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////
