//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_L_Looter_Rifle_F;
    class I_L_Looter_Rifle_F_OCimport_01 : I_L_Looter_Rifle_F { scope = 0; class EventHandlers; };
    class I_L_Looter_Rifle_F_OCimport_02 : I_L_Looter_Rifle_F_OCimport_01 { class EventHandlers; };

    class Atlas_I_UNO_MRAP_01_F;
    class Atlas_I_UNO_MRAP_01_F_OCimport_01 : Atlas_I_UNO_MRAP_01_F { scope = 0; class EventHandlers; };
    class Atlas_I_UNO_MRAP_01_F_OCimport_02 : Atlas_I_UNO_MRAP_01_F_OCimport_01 { scope = 0; class EventHandlers; };

    class Atlas_I_UNO_MRAP_01_hmg_F;
    class Atlas_I_UNO_MRAP_01_hmg_F_OCimport_01 : Atlas_I_UNO_MRAP_01_hmg_F { scope = 0; class EventHandlers; class Turrets; };
    class Atlas_I_UNO_MRAP_01_hmg_F_OCimport_02 : Atlas_I_UNO_MRAP_01_hmg_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class Atlas_I_UNO_Offroad_01_F;
    class Atlas_I_UNO_Offroad_01_F_OCimport_01 : Atlas_I_UNO_Offroad_01_F { scope = 0; class EventHandlers; class Turrets; };
    class Atlas_I_UNO_Offroad_01_F_OCimport_02 : Atlas_I_UNO_Offroad_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class Atlas_I_UNO_Offroad_armed_01_F;
    class Atlas_I_UNO_Offroad_armed_01_F_OCimport_01 : Atlas_I_UNO_Offroad_armed_01_F { scope = 0; class EventHandlers; class Turrets; };
    class Atlas_I_UNO_Offroad_armed_01_F_OCimport_02 : Atlas_I_UNO_Offroad_armed_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class M2_Turret;
        };
    };

    class Atlas_I_UNO_Offroad_01_comms_F;
    class Atlas_I_UNO_Offroad_01_comms_F_OCimport_01 : Atlas_I_UNO_Offroad_01_comms_F { scope = 0; class EventHandlers; class Turrets; };
    class Atlas_I_UNO_Offroad_01_comms_F_OCimport_02 : Atlas_I_UNO_Offroad_01_comms_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class O_APC_Tracked_02_cannon_F;
    class O_APC_Tracked_02_cannon_F_OCimport_01 : O_APC_Tracked_02_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class O_APC_Tracked_02_cannon_F_OCimport_02 : O_APC_Tracked_02_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class O_APC_Wheeled_02_rcws_v2_F;
    class O_APC_Wheeled_02_rcws_v2_F_OCimport_01 : O_APC_Wheeled_02_rcws_v2_F { scope = 0; class EventHandlers; class Turrets; };
    class O_APC_Wheeled_02_rcws_v2_F_OCimport_02 : O_APC_Wheeled_02_rcws_v2_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class O_Heli_Light_02_dynamicLoadout_F;
    class O_Heli_Light_02_dynamicLoadout_F_OCimport_01 : O_Heli_Light_02_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Heli_Light_02_dynamicLoadout_F_OCimport_02 : O_Heli_Light_02_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class I_Heli_Light_01_dynamicLoadout_F;
    class I_Heli_Light_01_dynamicLoadout_F_OCimport_01 : I_Heli_Light_01_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_Light_01_dynamicLoadout_F_OCimport_02 : I_Heli_Light_01_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class I_Heli_Light_01_F;
    class I_Heli_Light_01_F_OCimport_01 : I_Heli_Light_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_Light_01_F_OCimport_02 : I_Heli_Light_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class Aegis_I_Heli_Transport_02_Heavy_F;
    class Aegis_I_Heli_Transport_02_Heavy_F_OCimport_01 : Aegis_I_Heli_Transport_02_Heavy_F { scope = 0; class EventHandlers; class Turrets; };
    class Aegis_I_Heli_Transport_02_Heavy_F_OCimport_02 : Aegis_I_Heli_Transport_02_Heavy_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class I_Heli_Attack_03_F;
    class I_Heli_Attack_03_F_OCimport_01 : I_Heli_Attack_03_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_Attack_03_F_OCimport_02 : I_Heli_Attack_03_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_Crocus_AT;
    class I_Crocus_AT_OCimport_01 : I_Crocus_AT { scope = 0; class EventHandlers; };
    class I_Crocus_AT_OCimport_02 : I_Crocus_AT_OCimport_01 { scope = 0; class EventHandlers; };

    class I_Crocus_AP;
    class I_Crocus_AP_OCimport_01 : I_Crocus_AP { scope = 0; class EventHandlers; };
    class I_Crocus_AP_OCimport_02 : I_Crocus_AP_OCimport_01 { scope = 0; class EventHandlers; };

    class I_GMG_01_high_F;
    class I_GMG_01_high_F_OCimport_01 : I_GMG_01_high_F { scope = 0; class EventHandlers; class Turrets; };
    class I_GMG_01_high_F_OCimport_02 : I_GMG_01_high_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_HMG_01_high_F;
    class I_HMG_01_high_F_OCimport_01 : I_HMG_01_high_F { scope = 0; class EventHandlers; class Turrets; };
    class I_HMG_01_high_F_OCimport_02 : I_HMG_01_high_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_Mortar_01_F;
    class I_Mortar_01_F_OCimport_01 : I_Mortar_01_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Mortar_01_F_OCimport_02 : I_Mortar_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_static_AA_F;
    class I_static_AA_F_OCimport_01 : I_static_AA_F { scope = 0; class EventHandlers; class Turrets; };
    class I_static_AA_F_OCimport_02 : I_static_AA_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_static_AT_F;
    class I_static_AT_F_OCimport_01 : I_static_AT_F { scope = 0; class EventHandlers; class Turrets; };
    class I_static_AT_F_OCimport_02 : I_static_AT_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class I_American_Resisten_RIfleman_01 : I_L_Looter_Rifle_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "RIfleman";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"Aegis_arifle_M4A1_grip_F","hgun_G17_black_F"};
        respawnWeapons[] = {"Aegis_arifle_M4A1_grip_F","hgun_G17_black_F"};

        magazines[] = {"30Rnd_556x45_Stanag_green","17Rnd_9x21_Mag","30Rnd_556x45_Stanag_green","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag_green","17Rnd_9x21_Mag","30Rnd_556x45_Stanag_green","17Rnd_9x21_Mag"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"Aegis_arifle_M4A1_grip_F","CUP_muzzle_snds_M16","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","CUP_optic_HoloBlack",{"30Rnd_556x45_Stanag_green",30},{},""},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"30Rnd_556x45_Stanag_green",3,30},{"17Rnd_9x21_Mag",1,17}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"30Rnd_556x45_Stanag_green",5,30},{"17Rnd_9x21_Mag",2,17}}},{"B_ViperHarness_oli_F",{}},"H_Booniehat_wdl","",{},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_Heavy_Rifleman_01 : I_American_Resisten_RIfleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy Rifleman";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"arifle_SCAR_short_khaki_F","hgun_G17_black_F"};
        respawnWeapons[] = {"arifle_SCAR_short_khaki_F","hgun_G17_black_F"};

        magazines[] = {"20Rnd_762x51_Mag","17Rnd_9x21_Mag","20Rnd_762x51_Mag","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"20Rnd_762x51_Mag","17Rnd_9x21_Mag","20Rnd_762x51_Mag","17Rnd_9x21_Mag"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_SCAR_short_khaki_F","muzzle_snds_B","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","CUP_optic_Eotech553_Black",{"20Rnd_762x51_Mag",20},{},""},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17},{"20Rnd_762x51_Mag",2,20}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"17Rnd_9x21_Mag",2,17},{"20Rnd_762x51_Mag",6,20}}},{"B_ViperHarness_oli_F",{}},"H_Booniehat_wdl","G_Bandanna_RedFlame2",{},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_TAB_75RGR_2BTN'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_TAB_75RGR_2BTN";

    };

    class I_American_Resisten_AT_Rifleman_01 : I_American_Resisten_RIfleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT Rifleman";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"Aegis_arifle_M4A1_short_F","launch_MRAWS_olive_F","hgun_G17_black_F"};
        respawnWeapons[] = {"Aegis_arifle_M4A1_short_F","launch_MRAWS_olive_F","hgun_G17_black_F"};

        magazines[] = {"30Rnd_556x45_Stanag_green","MRAWS_HEAT_F","17Rnd_9x21_Mag","30Rnd_556x45_Stanag_green","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag_green","MRAWS_HEAT_F","17Rnd_9x21_Mag","30Rnd_556x45_Stanag_green","17Rnd_9x21_Mag"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"Aegis_arifle_M4A1_short_F","CUP_muzzle_snds_M16","CUP_acc_ANPEQ_15_Top_Flashlight_Black_L","CUP_optic_Elcan_SpecterDR_black",{"30Rnd_556x45_Stanag_green",30},{},""},{"launch_MRAWS_olive_F","","","",{"MRAWS_HEAT_F",1},{},""},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17},{"30Rnd_556x45_Stanag_green",3,30}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"17Rnd_9x21_Mag",2,17},{"30Rnd_556x45_Stanag_green",8,30}}},{"B_ViperHarness_oli_F",{{"MRAWS_HEAT_F",4,1}}},"H_Booniehat_wdl","G_Sport_Blackyellow",{},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_Medic_01 : I_American_Resisten_RIfleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"SMG_04_khk_F","hgun_G17_black_F"};
        respawnWeapons[] = {"SMG_04_khk_F","hgun_G17_black_F"};

        magazines[] = {"40Rnd_460x30_Mag_F","17Rnd_9x21_Mag","40Rnd_460x30_Mag_F","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"40Rnd_460x30_Mag_F","17Rnd_9x21_Mag","40Rnd_460x30_Mag_F","17Rnd_9x21_Mag"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"SMG_04_khk_F","Aegis_muzzle_snds_460_khaki","CUP_acc_ANPEQ_15_Top_Flashlight_OD_L","Aegis_optic_ICO_khaki",{"40Rnd_460x30_Mag_F",40},{},""},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17},{"40Rnd_460x30_Mag_F",2,40}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"17Rnd_9x21_Mag",2,17},{"40Rnd_460x30_Mag_F",8,40}}},{"B_ViperHarness_oli_F",{{"Medikit",3},{"FirstAidKit",2},{"ALIVE_Tablet",1}}},"H_Booniehat_wdl","G_Bandanna_shades",{},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_Marksman_01 : I_American_Resisten_RIfleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"Aegis_arifle_SR25_MR_khk_F","CUP_hgun_UZI","Laserdesignator_03"};
        respawnWeapons[] = {"Aegis_arifle_SR25_MR_khk_F","CUP_hgun_UZI","Laserdesignator_03"};

        magazines[] = {"20Rnd_762x51_Mag","CUP_32Rnd_9x19_UZI_M","Laserbatteries","20Rnd_762x51_Mag","CUP_32Rnd_9x19_UZI_M","Laserbatteries"};
        respawnMagazines[] = {"20Rnd_762x51_Mag","CUP_32Rnd_9x19_UZI_M","Laserbatteries","20Rnd_762x51_Mag","CUP_32Rnd_9x19_UZI_M","Laserbatteries"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"Aegis_arifle_SR25_MR_khk_F","","CUP_acc_ANPEQ_15_OD","CUP_optic_LeupoldM3LR",{"20Rnd_762x51_Mag",20},{},""},{},{"CUP_hgun_UZI","CUP_muzzle_snds_UZI","","optic_Yorris",{"CUP_32Rnd_9x19_UZI_M",32},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"20Rnd_762x51_Mag",2,20}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"20Rnd_762x51_Mag",6,20},{"CUP_32Rnd_9x19_UZI_M",3,32}}},{"B_ViperHarness_oli_F",{}},"H_Booniehat_wdl","",{"Laserdesignator_03","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_Autorifleman_01 : I_American_Resisten_RIfleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"LMG_Mk200_khk_F","hgun_G17_black_F","Binocular"};
        respawnWeapons[] = {"LMG_Mk200_khk_F","hgun_G17_black_F","Binocular"};

        magazines[] = {"200Rnd_65x39_cased_Box","17Rnd_9x21_Mag","200Rnd_65x39_cased_Box","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"200Rnd_65x39_cased_Box","17Rnd_9x21_Mag","200Rnd_65x39_cased_Box","17Rnd_9x21_Mag"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"LMG_Mk200_khk_F","muzzle_snds_H_khk_F","Aegis_acc_pointer_DM_Khaki","Aegis_optic_ICO_khaki",{"200Rnd_65x39_cased_Box",200},{},""},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"17Rnd_9x21_Mag",2,17},{"200Rnd_65x39_cased_Box",2,200}}},{"B_ViperHarness_oli_F",{{"200Rnd_65x39_cased_Box",3,200}}},"H_Booniehat_wdl","",{"Binocular","","","",{},{},""},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_Machine_gunner_01 : I_American_Resisten_Autorifleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine gunner";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_OCarrierLuchnik_Lite_grn_F","H_Booniehat_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"MMG_02_khaki_F","hgun_G17_black_F","Binocular"};
        respawnWeapons[] = {"MMG_02_khaki_F","hgun_G17_black_F","Binocular"};

        magazines[] = {"130Rnd_338_Mag","17Rnd_9x21_Mag","130Rnd_338_Mag","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"130Rnd_338_Mag","17Rnd_9x21_Mag","130Rnd_338_Mag","17Rnd_9x21_Mag"};

        backpack = "B_ViperHarness_oli_F";

        ALiVE_orbatCreator_loadout[] = {{"MMG_02_khaki_F","muzzle_snds_338_green","Aegis_acc_pointer_DM_Khaki","optic_Holosight_lush_F",{"130Rnd_338_Mag",100},{},"bipod_01_F_khk"},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17}}},{"Aegis_V_OCarrierLuchnik_Lite_grn_F",{{"17Rnd_9x21_Mag",2,17},{"130Rnd_338_Mag",3,100}}},{"B_ViperHarness_oli_F",{{"130Rnd_338_Mag",3,100}}},"H_Booniehat_wdl","",{"Binocular","","","",{},{},""},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_Hunter_01 : Atlas_I_UNO_MRAP_01_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hunter";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\soft_F_Exp\MRAP_01\data\MRAP_01_base_olive_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_F_Exp\MRAP_01\data\MRAP_01_adds_olive_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Data_F_Exp\Vehicles\Turret_olive_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class I_American_Resisten_Hunter_HMG_01 : Atlas_I_UNO_MRAP_01_hmg_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hunter HMG";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\soft_F_Exp\MRAP_01\data\MRAP_01_base_olive_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_F_Exp\MRAP_01\data\MRAP_01_adds_olive_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Data_F_Exp\Vehicles\Turret_olive_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class I_American_Resisten_Hunter_GMG_01 : Atlas_I_UNO_MRAP_01_hmg_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hunter GMG";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\soft_F_Exp\MRAP_01\data\MRAP_01_base_olive_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_F_Exp\MRAP_01\data\MRAP_01_adds_olive_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Data_F_Exp\Vehicles\Turret_olive_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class I_American_Resisten_Offroad_01 : Atlas_I_UNO_Offroad_01_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_offroad_HMG_01 : Atlas_I_UNO_Offroad_armed_01_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "offroad HMG";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_Offroad_comms_01 : Atlas_I_UNO_Offroad_01_comms_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Offroad comms";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_grn_CO.paa'];_unit setObjectTextureGlobal [2,'a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_cover_grn_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_BTR_Kcaptured_01 : O_APC_Tracked_02_cannon_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "BTR-K captured";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3_Aegis\Armor_F_Aegis\APC_Tracked_02\Data\APC_Tracked_02_ext_01_RUkhk_CO.paa'];_unit setObjectTextureGlobal [1,'\A3_Aegis\Armor_F_Aegis\APC_Tracked_02\Data\APC_Tracked_02_ext_02_RUkhk_CO.paa'];_unit setObjectTextureGlobal [2,'\A3_Aegis\Armor_F_Aegis\APC_Tracked_02\Data\RCWS30_RUkhk_CO.paa'];_unit setObjectTextureGlobal [3,'\A3_Aegis\Armor_F_Aegis\Data\camonet_RUS_green_CO.paa'];_unit setObjectTextureGlobal [4,'\A3_Aegis\Armor_F_Aegis\Data\cage_RUkhk_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_Crewman_01 : I_American_Resisten_RIfleman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_ChestrigEast_ghex_F","H_HelmetSpecB_light_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};
        respawnlinkedItems[] = {"Aegis_V_ChestrigEast_ghex_F","H_HelmetSpecB_light_wdl","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch","CUP_NVG_PVS7"};

        weapons[] = {"sgun_M4_F","hgun_G17_black_F"};
        respawnWeapons[] = {"sgun_M4_F","hgun_G17_black_F"};

        magazines[] = {"8Rnd_12Gauge_Pellets","17Rnd_9x21_Mag","8Rnd_12Gauge_Pellets","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"8Rnd_12Gauge_Pellets","17Rnd_9x21_Mag","8Rnd_12Gauge_Pellets","17Rnd_9x21_Mag"};

        backpack = "B_AssaultPack_Enh_tna_F";

        ALiVE_orbatCreator_loadout[] = {{"sgun_M4_F","","","CUP_optic_HoloBlack",{"8Rnd_12Gauge_Pellets",8},{},""},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17},{"8Rnd_12Gauge_Pellets",2,8}}},{"Aegis_V_ChestrigEast_ghex_F",{{"17Rnd_9x21_Mag",2,17},{"8Rnd_12Gauge_Pellets",6,8},{"8Rnd_12Gauge_Slug",4,8}}},{"B_AssaultPack_Enh_tna_F",{{"8Rnd_12Gauge_Pellets",3,8},{"17Rnd_9x21_Mag",3,17},{"8Rnd_12Gauge_Slug",3,8}}},"H_HelmetSpecB_light_wdl","G_Bandanna_blk",{},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch","CUP_NVG_PVS7"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_MSE_3Captured_01 : O_APC_Wheeled_02_rcws_v2_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "MSE-3 Captured";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Crewman_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_Crewman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3_Aegis\Armor_F_Aegis\APC_Wheeled_02\Data\APC_Wheeled_02_ext_01_RUkhk_CO.paa'];_unit setObjectTextureGlobal [1,'\A3_Aegis\Armor_F_Aegis\APC_Wheeled_02\Data\APC_Wheeled_02_ext_02_RUkhk_CO.paa'];_unit setObjectTextureGlobal [2,'\A3_Aegis\Soft_F_Aegis\UGV_01\Data\Turret_RUkhk_CO.paa'];_unit setObjectTextureGlobal [3,'\A3_Aegis\Armor_F_Aegis\Data\camonet_RUS_green_CO.paa'];_unit setObjectTextureGlobal [4,'\A3_Aegis\Armor_F_Aegis\Data\cage_RUkhk_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_PO_30_Captured_01 : O_Heli_Light_02_dynamicLoadout_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "PO-30 Captured";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "I_American_Resisten_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3_Aegis\Air_F_Aegis\Heli_Light_02\Data\Heli_Light_02_ext_raven_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_Pilot_01 : I_American_Resisten_Crewman_01 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 2;
        faction = "I_America";

        identityTypes[] = {"Head_Euro","LanguagePOL_F","G_LOOTER_default"};

        uniformClass = "eou_gorka_26";

        linkedItems[] = {"Aegis_V_ChestrigEast_ghex_F","H_PilotHelmetFighter_I_I","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch"};
        respawnlinkedItems[] = {"Aegis_V_ChestrigEast_ghex_F","H_PilotHelmetFighter_I_I","ItemMap","ItemSmartPhone","ItemRadio","ItemWatch"};

        weapons[] = {"SMG_04_khk_F","hgun_G17_black_F"};
        respawnWeapons[] = {"SMG_04_khk_F","hgun_G17_black_F"};

        magazines[] = {"40Rnd_460x30_Mag_F","17Rnd_9x21_Mag","40Rnd_460x30_Mag_F","17Rnd_9x21_Mag"};
        respawnMagazines[] = {"40Rnd_460x30_Mag_F","17Rnd_9x21_Mag","40Rnd_460x30_Mag_F","17Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"SMG_04_khk_F","","","CUP_optic_Eotech553_OD",{"40Rnd_460x30_Mag_F",40},{},""},{},{"hgun_G17_black_F","CUP_muzzle_snds_M9","","",{"17Rnd_9x21_Mag",17},{},""},{"eou_gorka_26",{{"FirstAidKit",1},{"17Rnd_9x21_Mag",1,17},{"40Rnd_460x30_Mag_F",2,40}}},{"Aegis_V_ChestrigEast_ghex_F",{{"17Rnd_9x21_Mag",2,17},{"40Rnd_460x30_Mag_F",1,40}}},{},"H_PilotHelmetFighter_I_I","",{},{"ItemMap","ItemSmartPhone","ItemRadio","","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'USP_PATCH_USA_MORALE_HATE_US_OCP'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "USP_PATCH_USA_MORALE_HATE_US_OCP";

    };

    class I_American_Resisten_AH_9_01 : I_Heli_Light_01_dynamicLoadout_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "AH-9";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "I_American_Resisten_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F\Heli_Light_01\Data\Heli_Light_01_ext_BLUFOR_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Air_F\Heli_Light_01\Data\Heli_Light_01_dot_CA.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Blu";

    };

    class I_American_Resisten_MH_9_01 : I_Heli_Light_01_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "MH-9";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "I_American_Resisten_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F\Heli_Light_01\Data\Heli_Light_01_ext_BLUFOR_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Blu";

    };

    class I_American_Resisten_CH_49E_01 : Aegis_I_Heli_Transport_02_Heavy_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "CH-49E";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "I_American_Resisten_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3_Aegis\air_f_Aegis\Heli_Transport_02\data\Skins\Heli_Transport_02_ext_01_Green_CO.paa'];_unit setObjectTextureGlobal [1,'\A3_Aegis\air_f_Aegis\Heli_Transport_02\data\Skins\Heli_Transport_02_ext_02_Green_CO.paa'];_unit setObjectTextureGlobal [2,'\A3_Aegis\air_f_Aegis\Heli_Transport_02\data\Skins\Heli_Transport_02_ext_02_Green_CO.paa'];_unit setObjectTextureGlobal [3,'\A3_Aegis\air_f_Aegis\Heli_Transport_02\data\Heli_Transport_02_int_02_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class I_American_Resisten_AH_1_01 : I_Heli_Attack_03_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "AH-1";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_Pilot_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3_Atlas\Air_F_Atlas\Heli_Attack_03\Data\Heli_Attack_03_Body_ADF_CO.paa'];_unit setObjectTextureGlobal [1,'\A3_Atlas\Air_F_Atlas\Heli_Attack_03\Data\Heli_Attack_03_details_ADF_CO.paa'];_unit setObjectTextureGlobal [2,'\A3_Atlas\Air_F_Atlas\Heli_Attack_03\Data\Heli_Attack_03_adds_ADF_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "ADF";

    };

    class I_American_Resisten_Crocus_AT_01 : I_Crocus_AT_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crocus AT";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_American_Resisten_Crocus_AP_01 : I_Crocus_AP_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crocus AP";
        side = 2;
        faction = "I_America";
        crew = "I_American_Resisten_RIfleman_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_American_Resisten_MK32_GMG_01 : I_GMG_01_high_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "MK32 GMG ";
        side = 2;
        faction = "I_America";
        crew = "I_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_American_Resisten_MK30_HMG_02 : I_HMG_01_high_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "MK30 HMG";
        side = 2;
        faction = "I_America";
        crew = "I_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_American_Resisten_Mk6_mortar_01 : I_Mortar_01_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mk6 mortar";
        side = 2;
        faction = "I_America";
        crew = "I_soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_American_Resisten_MK3_AA_01 : I_static_AA_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "MK3 AA";
        side = 2;
        faction = "I_America";
        crew = "I_soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_American_Resisten_MK3_AT_01 : I_static_AT_F_OCimport_02 {
        author = "pvtJ.shark";
        scope = 2;
        scopeCurator = 2;
        displayName = "MK3 AT";
        side = 2;
        faction = "I_America";
        crew = "I_soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_American_Resisten_RIfleman_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////
